add word 'async' & code formatting
shimohq/chinese-programmer-wrong-pronunciation pull request #318
Opened 2021-04-07 14:49 UTC by haochengxia

1. 添加了async这个词；
2. 根据PEP8格式化addword.py，单双引号则是在不必要使用双引号的地方都统一成了单引号。

2021-04-07 16:46 UTC, liyishuai requested changes

2021-04-07 16:46 UTC, liyishuai commented on README.md
> +| async | [🔊](https://dict.youdao.com/dictvoice?audio=async&type=1) /əˈsɪŋk/ | [🔊](https://dict.youdao.com/dictvoice?audio=async&type=2) /æˈsɪŋk/ | ❌ /e'sɪŋk/ |
"Async" is short for "asynchronous" /eɪˈsɪŋkrənəs/, so /e'sɪŋk/ should not be wrong. Consider changing the wrong case into wrong stress?
```suggestion
| async | [🔊](https://dict.youdao.com/dictvoice?audio=async&type=1) /əˈsɪŋk/ | [🔊](https://dict.youdao.com/dictvoice?audio=async&type=2) /æˈsɪŋk/ | ❌ /'æsɪŋk/ |
```

2021-04-07 18:07 UTC, liyishuai approved these changes

2021-04-08 02:05 UTC, merged

2021-04-08 16:50 UTC, b1f6c1c4 commented
`async` should be /ˈeɪ ˈsɪŋk/

Evidence:

- https://youglish.com/pronounce/async/english
- https://en.wiktionary.org/wiki/asynchronous#English

2021-04-13 19:08 UTC, b1f6c1c4 commented
@liyishuai Please adjust `README.md` according to my comment above.

2021-04-13 19:17 UTC, liyishuai commented
Feel free to open a PR for that. I'm an external contributor without push access.